---
title: "Population data"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning= F, message = F)
rm(list=ls(all=TRUE))
library(dplyr)
mainDir <- "/Users/oliviazhang/Desktop/"
```


```{r,echo=F,message = FALSE}
#################################### Total population by county ####################################
### Cite: https://www.census.gov/data/datasets/time-series/demo/popest/2020s-state-detail.html#par_textimage
store_alldata <- read.csv(paste0(mainDir,"/MRP/pop_data/ACS_county_pop_est/cc-est2015-alldata.csv"))

# Select only 2011 population estimate
# 8 = 7/1/2015 population estimate
county_data <- store_alldata[store_alldata$YEAR==8,] 

# Select only old adults and relevant columns 
# 14 = Age 65 to 69 years 
# 15 = Age 70 to 74 years 
# 16 = Age 75 to 79 years 
# 17 = Age 80 to 84 years 
# 18 = Age 85 years or older
county_data <- county_data[county_data$AGEGRP==14 | county_data$AGEGRP==15 | county_data$AGEGRP==16 | county_data$AGEGRP==17 | county_data$AGEGRP==18, 
                           c("STATE",
                             "COUNTY",
                             "STNAME",
                             "CTYNAME",
                             "AGEGRP",
                             "TOT_POP",
                             "NHWA_MALE", #Not Hispanic, White alone
                             "NHIA_MALE", #Not Hispanic, American Indian, Alaska Native alone
                             "NHAA_MALE", #Not Hispanic, Asian alone
                             "NHNA_MALE", #Not Hispanic, Native Hawaiian, Other Pacific Islander alone
                             "NHTOM_MALE",#Not Hispanic, Two or More Races
                             "NHBA_MALE", #Not Hispanic, Black or African American alone
                             "H_MALE",    #Hispanic
                             "NHWA_FEMALE",
                             "NHIA_FEMALE",
                             "NHAA_FEMALE",
                             "NHNA_FEMALE",
                             "NHTOM_FEMALE",
                             "NHBA_FEMALE",
                             "H_FEMALE")]

# Recode age groups and FIPS
county_data$AGEGRP <- county_data$AGEGRP-13
county_data$fips <- as.numeric(county_data$STATE)*1000+as.numeric(county_data$COUNTY)
length(unique(county_data$fips))
```

```{r}
# check if sum up to total population
for (i in 1:nrow(county_data)){
  if (county_data$TOT_POP[i]-sum(county_data[i,7:20]) != 0){
    print(i)
}}
```

```{r}
fips <- unique(county_data$fips)
length(unique(county_data$fips))
```

### Acommodate for the county names which changed from 2011
```{r}
########################################  State-county IDs ########################################  
county_id <- read.csv(paste0(mainDir,"/MRP/pop_data/state_county_id/state_and_county_fips_master.csv"))
county_id <- county_id[complete.cases(county_id),]
```

```{r}
#deleted counties
county_id[!county_id$fips %in% fips,]

### Cite: https://www.census.gov/programs-surveys/geography/technical-documentation/county-changes.2010.html#list-tab-957819518 ###
county_id <- county_id[!county_id$name=="Bedford city",]
county_id[county_id$name=="Wade Hampton Census Area",] <- c(2158,"Kusilvak Census Area","AK")
county_id[county_id$name=="Shannon County" & county_id$state=="SD",] <- c(46102,"Oglala Lakota County","SD")
```



### Aggregate into 3 race categories as in NHATS

```{r,echo=F,message = FALSE}
#Non-Hispanic White/Other
county_data$NH_WO_Male <- county_data$NHWA_MALE + county_data$NHIA_MALE + county_data$NHAA_MALE + county_data$NHNA_MALE + county_data$NHTOM_MALE
county_data$NH_WO_Female <- county_data$NHWA_FEMALE + county_data$NHIA_FEMALE + county_data$NHAA_FEMALE + county_data$NHNA_FEMALE + county_data$NHTOM_FEMALE

#Non-Hispanic Black
county_data$NH_B_Male <- county_data$NHBA_MALE     #Not Hispanic, Black or African American alone 
county_data$NH_B_Female <- county_data$NHBA_FEMALE #Hispanic

#Hispanic
county_data$H_Male <- county_data$H_MALE
county_data$H_Female <- county_data$H_FEMALE

county_data$TOT_NH_WO <- county_data$NH_WO_Male + county_data$NH_WO_Female
county_data$TOT_NH_B <- county_data$NH_B_Male + county_data$NH_B_Female
county_data$TOT_H <- county_data$H_Male + county_data$H_Female
```


### Generate population data

```{r,echo=F}
#####################################  Empty pop data ##########################################
pop.data <- data.frame("fips" = rep(fips, each=15),
                       "age_label" = rep(rep(c("65-69", "70-74", "75-79", "80-84", "85+"), each = 3), 3142),
                       "age" = rep(rep(1:5, each = 3), 3142),
                       "race_label" = rep(rep(c("Non-Hispanic White/other", "Non-Hispanic Black", "Hispanic"),5),3142),
                       "race" = rep(rep(c(1:3),5),3142))
pop.data$N <- NA
pop.data <- merge(county_id, pop.data, by="fips")
pop.data
```



### Generate county-level population
```{r}
for (i in 1:length(fips)){
  for (j in 1:5){
      pop.data$N[pop.data$fips == fips[i] & pop.data$age == j] <- c(t(county_data[county_data$fips == fips[i]  & county_data$AGEGRP == j, c("TOT_NH_WO", "TOT_NH_B", "TOT_H")]))
  }
}
pop.data$N <- as.numeric(pop.data$N)
```



### Aggregate into census-division-level population
```{r,echo=F}
censusdiv_id <- read.csv(paste0(mainDir,"/MRP/pop_data/state_county_id/state_divisions.csv"))[,c("State.Code", "Division")]
colnames(censusdiv_id) <- c("state","division_label")
pop.data <- merge(censusdiv_id, pop.data, by="state")
length(unique(pop.data$fips))
```


```{r}
pop.data$division <- ifelse(pop.data$division_label == "New England", 1,
                            ifelse(pop.data$division_label == "Middle Atlantic", 2,
                                   ifelse(pop.data$division_label == "East North Central", 3,
                                          ifelse(pop.data$division_label == "West North Central", 4,
                                                                   ifelse(pop.data$division_label == "South Atlantic", 5,
                                                                          ifelse(pop.data$division_label == "East South Central", 6,
                                                                                 ifelse(pop.data$division_label == "West South Central", 7,
                                                                                        ifelse(pop.data$division_label == "Mountain", 8,
                                                                                               ifelse(pop.data$division_label == "Pacific", 9, NA)))))))))
```

```{r}
pop.data_ <- pop.data %>% group_by(division, race, age) %>% summarise(N = sum(N))
pop.data_<- pop.data_[,c("division", "age", "race", "N")]
pop.data_ <- pop.data_[with(pop.data_, order(division, age, race)),]
```


```{r}
#check if grouped correctly
sum(pop.data[pop.data$division == 2 & pop.data$age == 4 & pop.data$race == 2, "N"]) == c(pop.data_[pop.data_$division == 2 & pop.data_$age == 4 & pop.data_$race == 2, "N"])

sum(pop.data_$N) == sum(county_data$TOT_POP)
```


```{r}
saveRDS(pop.data_, file=paste0(mainDir,"/MRP/pop_data/pop.data.2015_v2.RData")) #1963486
```


```{r}
pop.data_$prop <- pop.data_$N/sum(pop.data_$N)
hist(pop.data_$prop, breaks = seq(0,max(pop.data_$prop)+0.001,by=0.001))
```
