---
title: "Bayesian Hierarchical Model with Poststratification"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning= F, message = F)
options(mc.cores = 3)
rm(list=ls(all=TRUE))
library(readstata13)
library(rstan)
library(fastDummies)
library(bayesplot)
seed <- 2023001
mainDir <- "/Users/oliviazhang/Desktop/"
```


## ------------------------------------------------------------------------------------------
## ----------------------------------- Prepare the data -------------------------------------
## ------------------------------------------------------------------------------------------

```{r,echo=F}
#Read in population data
pop.data <- readRDS(paste0(mainDir,"/MRP/pop_data/pop.data_v2.RData"))
#Read in outcome data
Round_1_data <- read.dta13(paste0(mainDir,"/MRP/2011_cohort/data/our_data_7439.dta"))
```


```{r,echo=F}
Round_1_data$age <- as.factor(Round_1_data$age)
Round_1_data$race <- as.factor(Round_1_data$race)
Round_1_data$division <- as.factor(Round_1_data$division)

Round_1_data$frailty <- Round_1_data$frailty+1
```

```{r,echo=F, results='hide'}
pop.data <- pop.data[,c("division", "age", "race", "N")]
pop.data <- pop.data[with(pop.data, order(division, age, race)),]
```

```{r,echo=F, results='hide'}
out.data <- Round_1_data[,c("division", "age", "race", "frailty")]
out.data <- out.data[with(out.data, order(division, age, race)),]
```


```{r,echo=F}
#Create dummy variables (not remove first dummy)
out.data.dum <- cbind(dummy_cols(out.data, remove_first_dummy = F,
                       select_columns = c("age","race","division")))
out.data.dum
pop.data.dum <- cbind(dummy_cols(pop.data, remove_first_dummy = F,
                       select_columns = c("age","race","division")))
pop.data.dum
```


## ------------------------------------------------------------------------------------------
## ---------------------------------- Model specification -----------------------------------
## ------------------------------------------------------------------------------------------

```{r,echo=F}
#Define parameters
outcome <- out.data.dum$frailty
N <- length(outcome)
K <- length(unique(outcome)) #3 levels of outcomes
P1 <- length(unique(Round_1_data$age)) #5 levels
P2 <- length(unique(Round_1_data$race)) #3 levels
D <- length(unique(Round_1_data$division)) #9 levels

X_0 <- as.matrix(as.integer(rep(1,N))) #intercept
X_1 <- as.matrix(out.data.dum[,5:9]) #age
X_2 <- as.matrix(out.data.dum[,10:12]) #race
Z <- as.matrix(out.data.dum[,13:21]) #division
```


```{r,echo=F}
n_iter <- 1000
n_chain <- 3
n_warmup <- 500
n_sim <- (n_iter-n_warmup) * n_chain
```


```{r,echo=F, message = FALSE, results='hide'}
stanfit <- stan(file=paste0(mainDir,"/MRP/stan_model_v6.stan"),
                data = list(N = N,
                          K = K,
                          D = D,
                          P1 = P1,
                          P2 = P2,
                          X_0 = X_0,
                          X_1 = X_1,
                          X_2 = X_2,
                          Z = Z,
                          outcome = outcome),
                iter=n_iter, chains=n_chain, warmup = n_warmup, seed = seed)
saveRDS(stanfit, file=paste0(mainDir,"/MRP/2011_cohort/data/stanfit_v6.RData"))

summary <- summary(stanfit)
saveRDS(summary, file=paste0(mainDir,"/MRP/2011_cohort/data/summary_v6.RData"))

post_samples <- rstan::extract(stanfit,
                         pars=c("b0","b_age","b_race","a"))
saveRDS(post_samples, file=paste0(mainDir,"/MRP/2011_cohort/data/post_samples_v6.RData"))
```



```{r}
# Trace plots
plot(stanfit, plotfun="trace", pars=c("sigma_b_age","sigma_b_race","sigma_a"))
```


```{r}
# ACF plots
stan_ac(stanfit, pars=c("sigma_b_age","sigma_b_race","sigma_a"))
```


```{r}
# Numerical diagnostics: R-hat
rhat(stanfit, pars=c("sigma_b_age","sigma_b_race","sigma_a"))
```



```{r,echo=F}
post_samples <- readRDS(paste0(mainDir,"/MRP/2011_cohort/data/post_samples_v6.RData"))
```


## ------------------------------------------------------------------------------------------
## ----------------------------------- Poststratification -----------------------------------
## ------------------------------------------------------------------------------------------

```{r}
n_pscell <- length(pop.data.dum$N)

eta <- array(NA, c(n_sim, n_pscell, 3))
eta[,,1] <- 0                            #normalize: set non-frail to 0

for(i in 1:n_sim){
    for(k in 1:2){
      b0 <- post_samples[["b0"]][i,1,k]    #1 coef
      b_age <- post_samples[["b_age"]][i,,k] #5 coef
      b_race <- post_samples[["b_race"]][i,,k] #3 coef
      a <- post_samples[["a"]][i,,k] #9 coef
      
      tmp.1 <- as.matrix(pop.data.dum[, 5:9])%*%as.matrix(b_age) #(135*5) * (5*1)
      tmp.2 <- as.matrix(pop.data.dum[, 10:12])%*%as.matrix(b_race)
      tmp.3 <- as.matrix(pop.data.dum[, 13:21])%*%as.matrix(a)      
      
      eta[i,,(k+1)] <- b0 + tmp.1 + tmp.2 + tmp.3 #(135*1)
    }
}

exp_eta <- exp(eta)                           #(5000*135*3)
```

```{r}
#transform to prevalence scale
ypred <- array(NA, c(n_sim, n_pscell, 3))

for(i in 1:n_sim){
  for(j in 1:n_pscell){
    sum <- sum(exp_eta[i,j,])
    ypred[i,j,] <- exp_eta[i,j,]/sum
  }
}
```

```{r}
#check if merge ypred correctly
which_cell <- 88
which_iter <- 416

tmp.b0 <- post_samples[["b0"]][which_iter,1,] #1*2
tmp.b_age <- post_samples[["b_age"]][which_iter,,] #5*2
tmp.b_race <- post_samples[["b_race"]][which_iter,,]  #3*2
tmp.a <- post_samples[["a"]][which_iter,,]  #9*2

tmp.1 <- as.matrix(pop.data.dum[which_cell, 5:9])%*%as.matrix(tmp.b_age) #(135*5) * (5*2)
tmp.2 <- as.matrix(pop.data.dum[which_cell, 10:12])%*%as.matrix(tmp.b_race)
tmp.3 <- as.matrix(pop.data.dum[which_cell, 13:21])%*%as.matrix(tmp.a) 

tmp.eta <- tmp.b0 + tmp.1 + tmp.2 + tmp.3 #(135*2)
tmp.exp_eta <- exp(tmp.eta)

c(1,tmp.exp_eta)/(sum(tmp.exp_eta)+1)==ypred[which_iter,which_cell,]
```

## ------------------------------------------------------------------------------------------
## ---------------------------------- Population estimate -----------------------------------
## ------------------------------------------------------------------------------------------

```{r,echo=F}
# Apply the census counts to weight each of the poststratification cells
# Then sum over all poststratification cells to obtain population estimate
  final_ps <- array(NA, c(n_sim, 3))
  
  for(i in 1:n_sim){
    for(k in 1:3){
      final_ps[i,k] <- sum(pop.data.dum$N*ypred[i,,k])/sum(pop.data.dum$N)
    }
  }

  # Calculate quantiles across the n_sim simulations to provide estimate and 95% CI
  pop_est <- data.frame("est"= NA,
                        "sd" = NA,
                        "CI_2.5" = NA,
                        "CI_50" = NA,
                        "CI_97.5" = NA)
  for (k in 1:3){
    mean <- round(mean(final_ps[,k]),5)
    q <- round(quantile(final_ps[,k], c(0.025,0.5,0.975)),5)
    sd <- round(sd(final_ps[,k]),5)
    pop_est <- rbind(pop_est, c(mean, sd, q[1], q[2], q[3]))
    }
  
  pop_est <- pop_est[-1,]
  row.names(pop_est) <- c("pi.1", "pi.2", "pi.3")
  pop_est
```

  
```{r}  
saveRDS(pop_est, file=paste0(mainDir,"/MRP/2011_cohort/data/results.3.v6.RData"))
```







